### ISSUE TITLE
AttributeError: 'Attn2Replace' object has no attribute 'set_new_condition'

### ISSUE THREAD

**Issue by lmc710731910** [cubiq/PuLID_ComfyUI#10]
Errors that occur when using ”JSONPuLID_IPAdapter_style_transfer.json“  in example , How to fix it

ComfyUI/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 146, in set_model_patch_replace
    to["patches_replace"]["attn2"][key].set_new_condition(**patch_kwargs)
AttributeError: 'Attn2Replace' object has no attribute 'set_new_condition'

**Comment by cubiq** [comment]
you need to update: ipadapter, pulid and instantid (if they are installed)

**Comment by lmc710731910** [comment]
Sorry for forgetting to look at your notes : "For IPAdapter compatibility you need to update the IPAdapter extension!"
hhh
Thank you very much
