### ISSUE TITLE
The difference result between PuLID_ComfyUI and official gradio demo 

### ISSUE THREAD

**Issue by rwywenyi** [cubiq/PuLID_ComfyUI#11]
![美女高清图像1723](https://github.com/cubiq/PuLID_ComfyUI/assets/136083041/0adcc190-b60e-4ddb-b310-7d327f8c618d)
![PuLID官方demo出图对比](https://github.com/cubiq/PuLID_ComfyUI/assets/136083041/a5f96df2-9a9e-4b3e-8e4c-99e701f58a06)
![PuLID comfyui插件出图对比](https://github.com/cubiq/PuLID_ComfyUI/assets/136083041/9100f637-33cc-42eb-ab68-fb3af7f67dd8)
![PuLID comfyui插件工作流](https://github.com/cubiq/PuLID_ComfyUI/assets/136083041/e7f489fd-ae9a-45af-8fa9-73b08977d2d7)

**Comment by rwywenyi** [comment]
Hello, thank you very much for providing so many excellent custom nodes. In the process of using PuLID comfyui,
1. I found that its face consistency effect is not as good as the official gradient demo;
2. The official code uses SDXL-lightning 4step UNet instead of UNet in SDXL, but PuLID custom node does not have this code and workflow. Is it because of this reason?

**Comment by cubiq** [comment]
you are using "neutral" method which is just for testing

**Comment by rwywenyi** [comment]
the difference between yours and offical code
<img width="904" alt="image" src="https://github.com/cubiq/PuLID_ComfyUI/assets/136083041/280b939e-903f-426e-b79b-fad645bdfb7e">

**Comment by cubiq** [comment]
the official repository doesn't have "neutral" you need to test with "style" or "fidelity"

**Comment by cubiq** [comment]
in the examples directory there's a workflow that replicates the gradio demo

**Comment by rwywenyi** [comment]
how to fix this bug?
![Uploading image.png…]()

**Comment by rwywenyi** [comment]
![image](https://github.com/cubiq/PuLID_ComfyUI/assets/136083041/94b1d693-e669-48e1-b7ae-210080a53586)
how can fix this bug?

**Comment by cubiq** [comment]
by reading the README file
