### ISSUE TITLE
I tried it with ipa's style migration and it works fine, but it's so slow, what's the reason?

### ISSUE THREAD

**Issue by jokero3answer** [cubiq/PuLID_ComfyUI#13]
![image](https://github.com/cubiq/PuLID_ComfyUI/assets/130854108/a0ceb66d-af76-4f37-8167-9628f80d73f6)

![image](https://github.com/cubiq/PuLID_ComfyUI/assets/130854108/ac8918a8-e38e-4a8e-9ffd-e02a6b9852fb)

![image](https://github.com/cubiq/PuLID_ComfyUI/assets/130854108/48641279-4620-4186-b3b8-fdcb1e7a5bf3)

**Comment by Phando** [comment]
Is this the PuLID_IPAdapter_style_transfer workflow? I have been unable to get it to work due to the following error...
'Attn2Replace' object has no attribute 'set_new_condition'
Have you run into that and is there a workaround?

**Comment by cubiq** [comment]
upgrade ipadapter. for speed use lightning/lcm/turbo models

**Comment by Phando** [comment]
After a fresh install of comfy and all the other junk, the IPAapter workflow is working. The PuLIDs ability to add and remove items from an image is amazing. Thank you!
