### ISSUE TITLE
The custome node is worse than origin PuLID

### ISSUE THREAD

**Issue by rwywenyi** [cubiq/PuLID_ComfyUI#15]
I hava tested many times:
I use PuLID_4-Step_lightning.json to generator image, the result is worse than origin PuLID
it is very hope to fix this bug

**Comment by friendlyFriend4000** [comment]
> I hava tested many times: I use PuLID_4-Step_lightning.json to generator image, the result is worse than origin PuLID it is very hope to fix this bug

Would you mind sharing more details with the issue you are having. You give very little material to work with.

**Comment by cubiq** [comment]
since the lack of feedback I'm closing this
