### ISSUE TITLE
Hope to support multiple image inputs

### ISSUE THREAD

**Issue by garbe-github-support** [cubiq/PuLID_ComfyUI#16]
![image](https://github.com/cubiq/PuLID_ComfyUI/assets/131808107/32d5038e-77e6-4e1b-ac22-e6283b248d28)
like this

**Comment by cubiq** [comment]
this is already supported

**Comment by ohenepee** [comment]
How do you do that? Will linking multiple load image nodes to the Apply Pulid node utilize all the images?
