### ISSUE TITLE
The issue with the final decoding step of Pulid

### ISSUE THREAD

**Issue by dh9527** [cubiq/PuLID_ComfyUI#20]
The issue with the final decoding step of Pulid, as I only have 4GB of graphics memory, I reported an error at the last step. Later, I switched to block decoding and succeeded. Is the example workflow more user-friendly by switching to VAE block decoding?

**Comment by dh9527** [comment]
[PuLID_IPAdapter_style_transfer.json](https://github.com/cubiq/PuLID_ComfyUI/blob/main/examples/PuLID_IPAdapter_style_transfer.json)

**Comment by cubiq** [comment]
4gb is really low for sdxl
