### ISSUE TITLE
Comfyui Import Failed

### ISSUE THREAD

**Issue by moviejimmy** [cubiq/PuLID_ComfyUI#21]
After installing PuLID from Comgyui manager and rerunning, I get the followig error:

0.0 seconds (IMPORT FAILED): C:\ComfyUI_cu121\ComfyUI\custom_nodes\PuLID_ComfyUI

Any idea what happened?

**Comment by cubiq** [comment]
check this https://github.com/cubiq/PuLID_ComfyUI/issues/1
