### ISSUE TITLE
 (IMPORT FAILED) PuLID_ComfyUI

### ISSUE THREAD

**Issue by Amaru-Zeas** [cubiq/PuLID_ComfyUI#29]
I also tried all the steps on the previously open issue but with no luck :( 

https://github.com/cubiq/PuLID_ComfyUI/issues/23

![image](https://github.com/cubiq/PuLID_ComfyUI/assets/131799050/4c8f5a8f-0ce7-42e5-92d9-cde70da30483)

**Comment by DaiNguyen1234** [comment]
Use from this https://github.com/cubiq/PuLID_ComfyUI/issues/23 and it's worked for me.

**Comment by cherishh** [comment]
https://github.com/cubiq/PuLID_ComfyUI/issues/23 works for me as well. Can you provide more information about your comfyui? i.e. are you using the default version of it, or the windows portable?
