### ISSUE TITLE
Vram management problem discussion.

### ISSUE THREAD

**Issue by inspire-boy** [cubiq/PuLID_ComfyUI#3]
This is very nice work!

I use both webui & comfy. 
In other side, Webui'extension was provided by HuChenlei. It's asesome. but where is Vram leak issue:
**https://github.com/Mikubill/sd-webui-controlnet/issues/2862**

I wonder if anyone can figure out what the problem is and give a fix. 

Thanks for all great work!

**Comment by cubiq** [comment]
you mean both versions have vram leak?

**Comment by inspire-boy** [comment]
> you mean both versions have vram leak?

problem only  in webui version , I found comfy work very well with pulid.

**Comment by cubiq** [comment]
okay then I'm closing this for now since it's not related to this extension
