### ISSUE TITLE
无法稳定下载EVA02_CLIP_L_336_psz14_s6B，手动下载后如何存放在huggingface的目录中

### ISSUE THREAD

**Issue by midweek1981** [cubiq/PuLID_ComfyUI#31]
EVA02_CLIP_L_336_psz14_s6B.pt已经手动下载了，但是不知道在huggingface的cachu目录中存放

**Comment by idea10101** [comment]
我也遇到了这个问题，不知道放在哪个目录

**Comment by cubiq** [comment]
at least you take the time to translate the messages...

**Comment by jwmemail** [comment]
> EVA02_CLIP_L_336_psz14_s6B.pt已经手动下载了，但是不知道在huggingface的cachu目录中存放

请问解决了吗

**Comment by zhangfeng0800** [comment]
First , you can make folder : ComfyUI\.cache\huggingface\hub\models--QuanSun--EVA-CLIP\snapshots\11afd202f2ae80869d6cef18b1ec775e79bd8d1\ , then put the EVA02_CLIP_L_336_psz14_s6B.pt here
Sencod , you touch a file named "main" in  ComfyUI\.cache\huggingface\hub\models--QuanSun--EVA-CLIP\refs\    ,  then modify the content of the file as follows: 11afd202f2ae80869d6cef18b1ec775e79bd8d1 
Then you can enjoy it 

https://zhuanlan.zhihu.com/p/697350603#/

**Comment by jpl1973jpl** [comment]
> First , you can make folder : ComfyUI \ .cache\huggingface\hub\models--QuanSun--EVA-CLIP\snapshots\11afd202f2ae80869d6cef18b1ec775e79bd8d1\ , then put the EVA02_CLIP_L_336_psz14_s6B.pt here Sencod , you touch a file named "main" in ComfyUI.cache\huggingface\hub\models--QuanSun--EVA-CLIP\refs\ , then modify the content of the file as follows: 11afd202f2ae80869d6cef18b1ec775e79bd8d1 Then you can enjoy it
> 
> https://zhuanlan.zhihu.com/p/697350603#/


Where can this main be found in which folder?

**Comment by HellOInDec** [comment]
> First , you can make folder : ComfyUI \ .cache\huggingface\hub\models--QuanSun--EVA-CLIP\snapshots\11afd202f2ae80869d6cef18b1ec775e79bd8d1\ , then put the EVA02_CLIP_L_336_psz14_s6B.pt here Sencod , you touch a file named "main" in ComfyUI.cache\huggingface\hub\models--QuanSun--EVA-CLIP\refs\ , then modify the content of the file as follows: 11afd202f2ae80869d6cef18b1ec775e79bd8d1 Then you can enjoy it
> 
> https://zhuanlan.zhihu.com/p/697350603#/

在Linux中，这个路径不对

**Comment by sailbeaver2023** [comment]
it didn't resolve the issue

**Comment by Alvinperson** [comment]
> EVA02_CLIP_L_336_psz14_s6B.pt已经手动下载了，但是不知道在huggingface的cachu目录中存放

"在huggingface的cachu目录中存放"是什么意思？不应该在电脑本地存放嘛？
