### ISSUE TITLE
missing nodes

### ISSUE THREAD

**Issue by lunatico67** [cubiq/PuLID_ComfyUI#34]
![Pulid](https://github.com/cubiq/PuLID_ComfyUI/assets/79542282/7ace054f-c3d5-4733-b4ec-cddd166bcfd0)

When i open a workflow appears these errors and i press in manager install missing custom nodes and apperas this:

![Pulid2](https://github.com/cubiq/PuLID_ComfyUI/assets/79542282/39f173bc-2eea-491d-8621-53871ee1d183)

**Comment by cubiq** [comment]
duplicate https://github.com/cubiq/PuLID_ComfyUI/issues/1
