### ISSUE TITLE
Error occurred when executing ApplyPulid:  unexpected EOF, expected 5572617 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by XTRMsavage** [cubiq/PuLID_ComfyUI#38]
I have re installed the extension, re downloaded the ip-adapter_pulidSDXL checkpoint, installed facelib, placed EVA02 Clip Model in the right place and the antelopev2 files. 

But I am still getting this error. 

<img width="962" alt="image" src="https://github.com/cubiq/PuLID_ComfyUI/assets/90519573/27ab0cf8-49c4-413f-a98c-98eb7c04a0da">

**Comment by cubiq** [comment]
this is likely a corrupted file

**Comment by KLimerencer** [comment]
same problem when executing ApplyPulid, how did u fix it

**Comment by cd0304** [comment]
i also have this problem, windows 11, python 3.11.4

**Comment by cd0304** [comment]
i have find the problem, antelopev2 model download error,have some file is not finish, download again,  it work ok!!!

**Comment by supergaozx** [comment]
I faced the same issue, and finally I fixed it.

The issue is due to corrupted weights files located in ..\python_embeded\Lib\site-packages\facexlib\weights

Delete all three .pth files, then run Pulid workflow.  It will automatically loaded the three files.

**Comment by runtimecai** [comment]
Sir, I have also encountered the same issue. Has this problem been resolved

**Comment by runtimecai** [comment]
> I faced the same issue, and finally I fixed it.
> 
> The issue is due to corrupted weights files located in ..\python_embeded\Lib\site-packages\facexlib\weights
> 
> Delete all three .pth files, then run Pulid workflow. It will automatically loaded the three files.

这个大佬的答案是对的，我是因为安装了两个版本的comfyui，第一次找错了位置了，打开serialization.py这个文档才发现，多谢大佬

**Comment by sh-xiaopeng** [comment]
> I faced the same issue, and finally I fixed it.我遇到了同样的问题，最后我解决了它。
> 
> The issue is due to corrupted weights files located in ..\python_embeded\Lib\site-packages\facexlib\weights此问题是由于位于 .. 中的权重文件损坏所致。\python_embeded\Lib\site-packages\facexlib\weights
> 
> Delete all three .pth files, then run Pulid workflow. It will automatically loaded the three files.删除所有三个 .pth 文件，然后运行 Pulid 工作流。它将自动加载这三个文件。

非常感谢你提出的解决方案，解决了困扰我一个通宵的问题
