### ISSUE TITLE
大佬能不能移植一下这个：https://github.com/tyxsspa/AnyText，到comfyui，这么好一个项目怎么没人弄呢，生成文字不是挺刚需的嘛。

### ISSUE THREAD

**Issue by 602387193c** [cubiq/PuLID_ComfyUI#39]
大佬能不能移植一下这个：https://github.com/tyxsspa/AnyText，到comfyui，这么好一个项目怎么没人弄呢，生成文字不是挺刚需的嘛。

**Comment by hben35096** [comment]
It's amazing (✪ω✪)
![image](https://github.com/cubiq/PuLID_ComfyUI/assets/139383150/5c0e9de8-e4d5-462a-bf98-8ee873c90e86)
![image](https://github.com/cubiq/PuLID_ComfyUI/assets/139383150/6262e7b8-e86e-45b8-87b5-0aaf30a1a79e)
