### ISSUE TITLE
An issue with style degradation

### ISSUE THREAD

**Issue by onefish51** [cubiq/PuLID_ComfyUI#40]
Thank you for your outstanding and great work.!

And I noticed that the ComfyUI version of pulid tends to degrade in style. For example, when specifying a cartoon style in the prompt, the Hugging Face demo can generate images with a distinct cartoon style, but in the ComfyUI version, most of the images generated still resemble real people.

ComfyUI workflow：
[workflow_xl_pulid.json](https://github.com/cubiq/PuLID_ComfyUI/files/15432108/workflow_xl_pulid.json)
input image:
![lecun](https://github.com/cubiq/PuLID_ComfyUI/assets/21029719/caf39892-75d3-4a96-b4d8-2ee3a7b1439b)
output compare:
![image](https://github.com/cubiq/PuLID_ComfyUI/assets/21029719/9de8a619-6a80-46cc-a7ff-4232eaebd4eb)

input image:
![lifeifei](https://github.com/cubiq/PuLID_ComfyUI/assets/21029719/983ec89d-cb7f-4cc7-b95e-d9333f3237b5)
output compare:
![image](https://github.com/cubiq/PuLID_ComfyUI/assets/21029719/5367f026-c37a-470b-a3fb-085fed00edb9)

**Comment by cubiq** [comment]
that depends mostly on the checkpoint realvis is not that good at extreme styles. The huggingface demo runs on dreamshaper
