### ISSUE TITLE
Dear programmer, can you develop the comfyui version of the Face-Adapter project, which is a powerful personalized ID project, if you can, I will sponsor it

### ISSUE THREAD

**Issue by rwywenyi** [cubiq/PuLID_ComfyUI#43]
<img width="892" alt="image" src="https://github.com/cubiq/PuLID_ComfyUI/assets/136083041/d858e1a0-3218-4290-8a46-c1bb81702afe">

**Comment by cubiq** [comment]
it's interesting, they do a lot of preprocessing before going into the actual generation, but it's still based on insighiface... if they need some help they can contact me
