### ISSUE TITLE
Error PulidEvaClipLoader: Consistency check failed: file should be of size 856461210 but has size 28449231 ((…)P_L_336_psz14_s6B.pt).

### ISSUE THREAD

**Issue by hong2610** [cubiq/PuLID_ComfyUI#51]
"Downloading (…)P_L_336_psz14_s6B.pt:   0%|"，EVA_CLIP “P_L_336_psz14_s6B.pt”Unable to automatically download。
thanks

**Comment by cubiq** [comment]
this is likely a temporary issue. the connection to the server failed. if you retry it should work

**Comment by hong2610** [comment]
> 这可能是暂时的问题。与服务器的连接失败。如果你重试它应该会起作用
That's right, it's a network problem. Thank u
