### ISSUE TITLE
Please 'pip install apex' prompt on console after installation

### ISSUE THREAD

**Issue by Shingkyo** [cubiq/PuLID_ComfyUI#55]
I got a prompt please 'pip install apex' on the console screen, but this PuLID runs fine without this on ComfyUI. I then proceed to install this Apex (Im using Windows), via python setup.py install after git clone this Apex. The previous warning about installing Apex is gone but PuLID cannot run after this and specifically got this warning: [No module named 'fused_layer_norm_cuda'] on my ComfyUI console. The Pytorch is 2.1.2 + CU 11.8.

I rolled back by uninstalling Apex, and PuLID works again. Im just wondering if a proper Apex actually speeds up the process? If yes, which version shall I install and how shall I do? Im not that tech-savvy and am just an average SD user. Please help... Thanks in advance.

**Comment by cubiq** [comment]
changed the error reporting

**Comment by liushh39** [comment]
i meet the same promple "No module named 'fused_layer_norm_cuda", how to fix it

**Comment by cubiq** [comment]
uninstall apex

**Comment by liushh39** [comment]
i run "pip uninstall apex", but still have this problem
<img width="984" alt="image" src="https://github.com/user-attachments/assets/d09a10f1-6174-4386-8329-f7a85e69f082">

**Comment by Shingkyo** [comment]
Maybe u try to see if it uninstalled with command pip list apex.. I saw from somewhere where they use command pip install cuda-python to resolve this issue if this Cuda-python package is not installed.

**Comment by tedtninety** [comment]
> uninstall apex

Thank you! You are a genius and WE appreciate you!
