### ISSUE TITLE
<img width="971" alt="123123123" src="https://github.com/cubiq/PuLID_ComfyUI/assets/125015943/5890a69f-4324-4d66-ac35-9c8ecf5a638f">

### ISSUE THREAD

**Issue by chaohuei2020** [cubiq/PuLID_ComfyUI#66]
<img width="971" alt="123123123" src="https://github.com/cubiq/PuLID_ComfyUI/assets/125015943/5890a69f-4324-4d66-ac35-9c8ecf5a638f">
重装这个就可以了

_Originally posted by @GonDesign in https://github.com/cubiq/PuLID_ComfyUI/issues/36#issuecomment-2207951365_

**Comment by cubiq** [comment]
I don't know what this is
