### ISSUE TITLE
EVA02-CLIP-L-14-336 Storage directory not found

### ISSUE THREAD

**Issue by 15953835029** [cubiq/PuLID_ComfyUI#75]
An instruction document that doesn't even bother to write the most basic configuration items, are you using this for people? If you can't pass the first configuration, how can you use the rest? As a developer don't you understand this?? If I can't access huggingface, I downloaded the model you need through some mirror sites, where do I need to store it??

**Comment by cubiq** [comment]
that's totally the right attitude to get help on a library that is completely free

**Comment by 15953835029** [comment]
> that's totally the right attitude to get help on a library that is completely free

In fact, you can optimize the description of the document, you look at so many problems in the comment area, in fact, many people are users, they do not know the address of your plug-in, let alone read the comments to go, do you think I blame you very aggrieved

**Comment by cubiq** [comment]
the community could help, it's not a one man show
