### ISSUE TITLE
已经导入PuLID_ComfyUI了comfyui还是报错

### ISSUE THREAD

**Issue by CLQ0525** [cubiq/PuLID_ComfyUI#76]
![Snipaste_2024-09-26_16-04-47](https://github.com/user-attachments/assets/c2e49590-6478-4809-80fc-cc5d436b991c)
![Snipaste_2024-09-26_16-05-15](https://github.com/user-attachments/assets/80a3b921-842b-4021-98f6-f1e19373cdec)

**Comment by cubiq** [comment]
I'm sorry guys I don't speak chinese
