### ISSUE TITLE
missing nodes? (everything updated)

### ISSUE THREAD

**Issue by peppepascale** [cubiq/PuLID_ComfyUI#81]
![image](https://github.com/user-attachments/assets/b268208b-a143-4b8b-b8bc-c19c56a37928)

**Comment by jeffufu** [comment]
Same issue here :)

**Comment by RodgerE1** [comment]
SAME

**Comment by cubiq** [comment]
guys, without error message I really can't say

**Comment by RodgerE1** [comment]
That's the thing, no error, it just says the nodes are missing. I verified all files are in the right place and the Flux version isn't working either. Thank You!!!
