### ISSUE TITLE
What's the difference between this custom node and the other Pulid ones?

### ISSUE THREAD

**Issue by ClothingAI** [cubiq/PuLID_ComfyUI#89]
- https://github.com/cubiq/PuLID_ComfyUI (yours)
- https://github.com/balazik/ComfyUI-PuLID-Flux (what about this one?)
- https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced (enhanced on top of previous one)

What's the difference between these? Thanks

**Comment by cchance27** [comment]
This was the main one for pulid, but the current implementation of flux doesn't jive well with comfyui, and requires a nasty monkeypatch to get it working so i think cubiq is holding off waiting for comfy to add the new hooks, so few other devs threw together hacks to get it working with flux while we all wait on comfy to add the hooks to clean things up :S

See #69

**Comment by ClothingAI** [comment]
> This was the main one for pulid, but the current implementation of flux doesn't jive well with comfyui, and requires a nasty monkeypatch to get it working so i think cubiq is holding off waiting for comfy to add the new hooks, so few other devs threw together hacks to get it working with flux while we all wait on comfy to add the hooks to clean things up :S
> 
> See #69

Interesting.
I am okay with having a single comfy installation that can run only pulid flux. and I am ready to do the monkeypatch of whatever that is. What can I do then?

**Comment by cchance27** [comment]
You don’t need a seperate comfy install or anything just be aware when you use the flux pulid nodes for now on a workflow it might break other nodes that also try to mess with the model, if you don’t use the node on a workflow it won’t do anything so no biggie to have it installed and play with

I’d say just use the enhanced one it adds some extra tweaks you can play with

**Comment by cubiq** [comment]
I'm closing this, thanks @cchance27
